name: cppWorkflow

on:
  push:
    branches: main
    paths:
      - 'cpp/**'

env:
  NUGETTOKEN: ${{ secrets.NUGET_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SCRIPTS_BASE_URL: https://raw.githubusercontent.com/linksplatform/Scripts/master/MultiProjectRepository

jobs:
  testCpp:
    runs-on: ubuntu-latest
    needs: findCppDirectory
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install conan
        run: pip install conan
      - name: Setup conan
        run: |
          conan profile new linksplatform --detect
          conan profile update settings.compiler=clang linksplatform
          conan profile update settings.compiler.version=13 linksplatform
          conan profile update settings.compiler.libcxx=libstdc++11 linksplatform
          conan profile update env.CXX=clang++ linksplatform
          conan profile show linksplatform
      - name: Instll conan packages
        run: |
          git clone https://github.com/linksplatform/conan-center-index
          cd conan-center-index && git checkout only-development && cd recipes
          conan create platform.interfaces/0.2.0+ platform.interfaces/0.2.5@ -pr=linksplatform
          conan create platform.ranges/all platform.ranges/0.1.3@ -pr=linksplatform
          conan create platform.random/all platform.random/0.1.0@ -pr=linksplatform
          conan create platform.collections/all platform.collections/0.1.0@ -pr=linksplatform
          conan create platform.collections.methods/all platform.collections.methods/0.1.0@ -pr=linksplatform
          conan create platform.converters/all platform.converters/0.1.0@ -pr=linksplatform
          conan create platform.threading/all platform.threading/0.1.0@ -pr=linksplatform
          conan create platform.memory/all platform.memory/0.1.0@ -pr=linksplatform
          conan create platform.data/all platform.data/0.1.0@ -pr=linksplatform
          conan create platform.delegates/all platform.delegates/0.1.3@ -pr=linksplatform
          conan create platform.setters/all platform.setters/0.0.1@ -pr=linksplatform
          conan create platform.equality/all platform.equality/0.0.1@ -pr=linksplatform
          conan create platform.exceptions/all platform.exceptions/0.2.0@ -pr=linksplatform
          conan create platform.hashing/all platform.hashing/0.2.0@ -pr=linksplatform
      - name: Test C++ and scan-build
        run: |
          $CXX=clang++
          $cmake_flags="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DLINKS_PLATFORM_TESTS=TRUE"
          $cmake_build_dir="build"
          cd cpp && mkdir $cmake_build_dir && cd $cmake_build_dir
          conan install $pwd/.. -pr=linksplatform --build=missing
          cmake .. $cmake_flags
          cmake --build .
          ls
  pushToNuget:
    runs-on: ubuntu-latest
    needs: testCpp
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Read Cpp package information
      run: |
        export REPOSITORY_NAME=$(basename ${{ github.repository }})
        wget "$SCRIPTS_BASE_URL/read_cpp_package_info.sh"
        bash ./read_cpp_package_info.sh
    - name: Publish Cpp NuGet package
      run: |
        export REPOSITORY_NAME=$(basename ${{ github.repository }})
        wget "$SCRIPTS_BASE_URL/push-cpp-nuget.sh"
        bash ./push-cpp-nuget.sh
